
services:
  test_db:
    build:
      context: .
      dockerfile: initdb/docker/test-postgis.Dockerfile
    container_name: postgis-test-db
    env_file: .env.test
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./osm_data:/osm_data
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 10


P