
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS polygons (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    client_id TEXT DEFAULT '0',
    geom GEOMETRY(POLYGON, 4326) NOT NULL
);
